// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParcelManagement.Infrastructure.Database;

#nullable disable

namespace ParcelManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251222124502_NotificationPrefInit")]
    partial class NotificationPrefInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ParcelManagement.Core.Entities.Locker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LockerName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LockerName")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Lockers");
                });

            modelBuilder.Entity("ParcelManagement.Core.Entities.NotificationPref", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsEmailActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsOnCheckInActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsOnClaimActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsOverdueActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsWhatsAppActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("QuiteHoursFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("QuiteHoursTo")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("NotificationPref");
                });

            modelBuilder.Entity("ParcelManagement.Core.Entities.Parcel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("EntryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("ExitDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LockerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ResidentUnitDeprecated")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<Guid>("ResidentUnitId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LockerId");

                    b.HasIndex("ResidentUnitId");

                    b.HasIndex("TrackingNumber")
                        .IsUnique();

                    b.ToTable("Parcels", t =>
                        {
                            t.HasCheckConstraint("CK_Parcels_LockerRequired", "(`Version` = 1) OR (`Version` > 1 AND `LockerId` IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ParcelManagement.Core.Entities.ResidentUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UnitName")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.ToTable("ResidentUnits");
                });

            modelBuilder.Entity("ParcelManagement.Core.Entities.TrackingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CustomEvent")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset>("EventTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ParcelId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PerformedByUser")
                        .HasColumnType("char(36)");

                    b.Property<string>("TrackingEventType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ParcelId");

                    b.HasIndex("PerformedByUser");

                    b.ToTable("TrackingEvents");
                });

            modelBuilder.Entity("ParcelManagement.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("longtext");

                    b.Property<string>("ResidentUnitDeprecated")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ParcelManagement.Core.Entities.UserResidentUnit", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ResidentUnitId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("UserId", "ResidentUnitId");

                    b.HasIndex("ResidentUnitId");

                    b.ToTable("UserResidentUnits");
                });

            modelBuilder.Entity("ParcelManagement.Core.Entities.Locker", b =>
                {
                    b.HasOne("ParcelManagement.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParcelManagement.Core.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("ParcelManagement.Core.Entities.NotificationPref", b =>
                {
                    b.HasOne("ParcelManagement.Core.Entities.User", "CreatingUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParcelManagement.Core.Entities.User", "UpdatingUser")
                        .WithOne()
                        .HasForeignKey("ParcelManagement.Core.Entities.NotificationPref", "UpdatedBy");

                    b.HasOne("ParcelManagement.Core.Entities.User", "User")
                        .WithOne("NotificationPref")
                        .HasForeignKey("ParcelManagement.Core.Entities.NotificationPref", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatingUser");

                    b.Navigation("UpdatingUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ParcelManagement.Core.Entities.Parcel", b =>
                {
                    b.HasOne("ParcelManagement.Core.Entities.Locker", "Locker")
                        .WithMany("Parcels")
                        .HasForeignKey("LockerId");

                    b.HasOne("ParcelManagement.Core.Entities.ResidentUnit", "ResidentUnit")
                        .WithMany("Parcels")
                        .HasForeignKey("ResidentUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Locker");

                    b.Navigation("ResidentUnit");
                });

            modelBuilder.Entity("ParcelManagement.Core.Entities.ResidentUnit", b =>
                {
                    b.HasOne("ParcelManagement.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParcelManagement.Core.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("ParcelManagement.Core.Entities.TrackingEvent", b =>
                {
                    b.HasOne("ParcelManagement.Core.Entities.Parcel", "Parcel")
                        .WithMany("TrackingEvents")
                        .HasForeignKey("ParcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParcelManagement.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("PerformedByUser");

                    b.Navigation("Parcel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ParcelManagement.Core.Entities.UserResidentUnit", b =>
                {
                    b.HasOne("ParcelManagement.Core.Entities.ResidentUnit", "ResidentUnit")
                        .WithMany("UserResidentUnits")
                        .HasForeignKey("ResidentUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParcelManagement.Core.Entities.User", "User")
                        .WithMany("UserResidentUnits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResidentUnit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ParcelManagement.Core.Entities.Locker", b =>
                {
                    b.Navigation("Parcels");
                });

            modelBuilder.Entity("ParcelManagement.Core.Entities.Parcel", b =>
                {
                    b.Navigation("TrackingEvents");
                });

            modelBuilder.Entity("ParcelManagement.Core.Entities.ResidentUnit", b =>
                {
                    b.Navigation("Parcels");

                    b.Navigation("UserResidentUnits");
                });

            modelBuilder.Entity("ParcelManagement.Core.Entities.User", b =>
                {
                    b.Navigation("NotificationPref");

                    b.Navigation("UserResidentUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
