name: CD Frontend — Production

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/cd-frontend.yml
    with:
      environment: production
    permissions:
      id-token: write
      contents: read
