name: cd-push-prod-backend

on: 
    push: 
        # branches: [main] disabling this for now since we're still in development 
    workflow_dispatch:

jobs: 
    build-and-push-image: 
        runs-on: [ubuntu-latest]
        environment: production
        steps: 
            - name: checkout code 
              uses: actions/checkout@v5

            - name: setup buildx 
              uses: docker/setup-buildx-action@v3

            - name: login into dockerhub
              uses: docker/login-action@v3
              with: 
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

            - name: build docker image 
              uses: docker/build-push-action@v6
              with: 
                context: ./backend/src
                file: ./backend/src/Dockerfile
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
                push: true
                cache-from: type=local,src=/tmp/.buildx-cache
                cache-to: type=local,dest=/tmp/.buildx-cache-new 

            - name: transfer new cache 
              run: |
                rm -rf /tmp/.buildx-cache
                mv /tmp/.buildx-cache-new /tmp/.buildx-cache 

            - name: logout dockerhub
              run: docker logout 
