name: cd-push-prod-frontend
on: 
    push: 
        branches: [main]
        paths: ['./frontend']
    workflow_dispatch:
jobs: 
    build-docker-image: 
        runs-on: ubuntu-latest 
        environment: production
        steps: 
            - name: checkout code 
              uses: actions/checkout@v5

            - name: setup buildx 
              uses: docker/setup-buildx-action@v3

            - name: login into dockerhub 
              uses: docker/login-action@v3
              with: 
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

            - name: build and push docker image 
              uses: docker/build-push-action@v6
              with: 
                context: ./frontend
                file: ./frontend/Dockerfile 
                tags: |
                    ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
                push: true
                cache-from: type=gha
                cache-to: type=gha,mode=max

            - name: logout docker 
              run: docker logout 