name: ci-push-frontend

on: 
    workflow_dispatch:

jobs: 
    build: 
        runs-on: ubuntu-latest 
        steps: 
            - name: checkout code 
              uses: actions/checkout@v5

            - name: setup node 
              uses: actions/setup-node@v5
              with: 
                node-version: 20

            - name: cache node modules 
              uses: actions/cache@v4
              with: 
                path: ~/.npm 
                key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json')}}

            - name: get dependencies 
              run: npm ci 
              working-directory: frontend 

            - name: run test
              run: npm run test:ci
              working-directory: frontend

            

            