name: ci-push-backend 

on: 
  push: 
    branches:
      - '**'
    paths:
      - 'backend/src'
      - '!backend/readme'
  workflow_dispatch:

jobs:
  build: 
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout-code'
        uses: 'actions/checkout@v5'

      - name: 'setup-dotnet'
        uses: 'actions/setup-dotnet@v5'
        with: 
          dotnet-version: '9.0.0'

      - name: 'get-dependencies'
        run: 'dotnet restore'
        working-directory: 'backend/src'

      - name: 'build-app'
        run: 'dotnet build --configuration Release --no-restore --warnaserror'
        working-directory: 'backend/src'

      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with: 
          name: build-output
          path: |
            backend/src/ParcelManagement.Api/bin/Release/net9.0
            backend/src/ParcelManagement.Core/bin/Release/net9.0
            backend/src/ParcelManagement.Infrastructure/bin/Release/net9.0
            backend/src/ParcelManagement.Test/bin/Release/net9.0

  test: 
    runs-on: 'ubuntu-latest'
    needs: 'build'
    steps: 
      - name: 'checkout-code'
        uses: 'actions/checkout@v5'

      - name: 'setup-dotnet'
        uses: 'actions/setup-dotnet@v5'
        with: 
          dotnet-version: '9.0.0'

      - name: 'download-artifact'
        uses: 'actions/download-artifact@v5'
        with: 
          name: 'build-output'
          path: '.'

      - name: 'run-test'
        run: 'dotnet test --configuration Release --no-build' 
        working-directory: 'backend/'



      

  


  